application: tack
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  static_files: app.html
  upload: app\.html

- url: /server
  script: server.py

- url: /(.*\.(css|js))
  static_files: \2/\1
  upload: (css|js)/(.*\.\1)
